services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: collabgrid
      MYSQL_USER: collab
      MYSQL_PASSWORD: collab
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    volumes:
      - minio_data:/data

  server:
    build:
      context: ./packages/server
    environment:
      PORT: 4000
      DATABASE_URL: mysql://collab:collab@mysql:3306/collabgrid
      DB_REQUIRE_MYSQL: "true"
      REDIS_URL: redis://redis:6379
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "4000:4000"
    depends_on:
      - mysql
      - redis
      - minio
    volumes:
      - ./packages/server:/app

  client:
    build:
      context: ./packages/client
    environment:
      VITE_API_BASE_URL: http://localhost:4000
      VITE_WS_URL: http://localhost:4000
    ports:
      - "5173:5173"
    depends_on:
      - server
    volumes:
      - ./packages/client:/app

volumes:
  mysql_data: {}
  redis_data: {}
  minio_data: {}

